### ISSUE TITLE
error running liberty:dev

### ISSUE THREAD

**Issue by tt-le** [OpenLiberty/guide-microprofile-openapi#102]
The following error appears when running `mvn liberty:dev` from the `start` directory.
```
[ERROR   ] CWWKO1659E: Failed to parse the OpenAPI document for application: guide-microprofile-openapi.
```
On `Launching defaultServer (Open Liberty 20.0.0.11/wlp-1.0.46.cl201120201014-1215) on OpenJDK 64-Bit Server VM, version 11.0.8+10 (en_CA)`

**Comment by gkwan-ibm** [comment]
close
- the issue was addressed
