### ISSUE TITLE
Deprecated API warning

### ISSUE THREAD

**Issue by tt-le** [OpenLiberty/guide-microprofile-openapi#104]
Running `mvn liberty:dev` in the `finish` directory generated the following warning:

```
[WARNING] guide-microprofile-openapi/finish/src/main/java/io/openliberty/guides/inventory/filter/InventoryOASFilter.java: guide-microprofile-openapi/finish/src/main/java/io/openliberty/guides/inventory/filter/InventoryOASFilter.java uses or overrides a deprecated API.
[WARNING] guide-microprofile-openapi/finish/src/main/java/io/openliberty/guides/inventory/filter/InventoryOASFilter.java: Recompile with -Xlint:deprecation for details.
```

**Comment by scottcurtis2605** [comment]
I have refactored the guide to resolve these issues on my personal fork, so the guide works with OpenAPI 2.0 in time for its GA release. This references & works with a local build of liberty which includes OpenAPI 2.0. However, I am waiting until the maven repository version of OpenLiberty includes OpenAPI 2.0 to make the pull request.

**Comment by gkwan-ibm** [comment]
close
- issue was fixed
