### ISSUE TITLE
OpenAPI 2.0 Support

### ISSUE THREAD

**Issue by scottcurtis2605** [OpenLiberty/guide-microprofile-openapi#106]
As `ServerVariables` will be removed in `2.0` (see [here](https://github.com/eclipse/microprofile-open-api/pull/348)) it is necessary to remove all references to `ServerVariables`, and update the guide to refer to `2.0` rather than `1.1`.

I have completed updating the guide with a local build of Open Liberty in a fork, though I am waiting for the maven repository to be updated with the latest release of Open Liberty, such that references to a local install are no longer required.

I have also noticed that #105 addresses the `ServerVariables` issue. I will link a PR once `2.0` is GA'd such that references to `1.1` can be updated within `server.xml` without issue.

**Comment by Azquelt** [comment]
There are also some cases where the guide uses `@APIResponse` which could be simplified by using `@APIResponseSchema` (added in 2.0) instead, or by removing the `content` attribute when it can be inferred from the method's return type.

**Comment by gkwan-ibm** [comment]
The guide does not use `ServerVariables` but need to be updated to use `@APIResponseSchema` and describe it

ref: https://openliberty.io/blog/2021/03/19/microprofile40-open-liberty-21003.html
