### ISSUE TITLE
Small issue with [Augmenting the existing JAX-RS annotations with OpenAPI annotations]

### ISSUE THREAD

**Issue by GarthJL1965** [OpenLiberty/guide-microprofile-openapi#141]
There's a small issue in https://openliberty.io/guides/microprofile-openapi.html#augmenting-the-existing-jax-rs-annotations-with-openapi-annotations

In [start] src/main/java/io/openliberty/guides/inventory/InventoryResource.java lines 30,31 from the documentation

```
import org.eclipse.microprofile.openapi.annotations.responses.APIResponse;
import org.eclipse.microprofile.openapi.annotations.responses.APIResponseSchema;
```

but in the actual repo 

```
import org.eclipse.microprofile.openapi.annotations.responses.APIResponse;
import org.eclipse.microprofile.openapi.annotations.responses.APIResponses; // << ** SEE HERE **
```

which causes 

```
C:\Users\GarthJL\Client\Code\guide-microprofile-openapi\start\src\main\java\io\openliberty\guides\inventory\InventoryResource.java:48: error: cannot find symbol
    @APIResponseSchema(value = Properties.class,
     ^
  symbol:   class APIResponseSchema
  location: class InventoryResource
C:\Users\GarthJL\Dominic\Code\guide-microprofile-openapi\start\src\main\java\io\openliberty\guides\inventory\InventoryResource.java:81: error: cannot find symbol
    @APIResponseSchema(value = InventoryList.class,
     ^
  symbol:   class APIResponseSchema
  location: class InventoryResource
2 errors
```

when the 2 x @APIResponseSchema annotations are added to that file 

Changing the 'APIResponses' to 'APIResponseSchema' fixes the issue.

I've attached my [windows] snips of the error, a compare between [start] and [finish] versions and a snip directly from the Github repo.

I can fork, fix on a branch & issue a PR if that is appropriate (if you're not using JIRA or such you might like to let me know what your branch convention is)

Cheers for the good work  

![liberty-dev-logs](https://user-images.githubusercontent.com/2327827/156978373-ed850eac-99be-4aeb-a632-9a5e60fc44ac.png)
![compare-start-finish](https://user-images.githubusercontent.com/2327827/156978311-d8b37678-9448-45ca-bcd4-6310e4c3bf22.png)
![Github-copy](https://user-images.githubusercontent.com/2327827/156978350-2138b61b-02c5-43ae-abe5-1d9a694a058c.png)

**Comment by gkwan-ibm** [comment]
Thank you @GarthJL1965 reported this issue. This issue was fixed.
