### ISSUE TITLE
Update guide for MP OpenAPI 3.1

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/guide-microprofile-openapi#154]
per comment from @Azquelt in https://github.com/OpenLiberty/docs/issues/5678, this guide should be updated to use version 3.1 with the 22.0.0.9 release.

**Comment by dmuelle** [comment]
FYI @gkwan-ibm

**Comment by Azquelt** [comment]
There's been a change to when we want to release `mpOpenAPI-3.1`. Originally we were targeting 22.0.0.9, but now we're going to wait and release it alongside the rest of MicroProfile 6.0.

**Comment by gkwan-ibm** [comment]
close
- the guide was updated to use `mpOpenAPI-3.1`
