### ISSUE TITLE
Attendee @JAX London reported test issue on Windows

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/guide-microprofile-openapi#169]
One attendee at JAX London could not get the tests to work on Windows machine. I checked the port was not in use. He said all of the guide tests he tried have the same problem.

**Comment by gkwan-ibm** [comment]
hi @Emily-Jiang 

Did the app work with the port 9080 and only the test fail? Or both the app and test did not work?

**Comment by Emily-Jiang** [comment]
It was the former.

**Comment by gkwan-ibm** [comment]
hi @Emily-Jiang 

We are investigating, but do you still have more info? e.g. console output from the dev mode or log files

**Comment by gkwan-ibm** [comment]
We cannot reproduce the problem on Win VM.

**Comment by Emily-Jiang** [comment]
> hi @Emily-Jiang
> 
> We are investigating, but do you still have more info? e.g. console output from the dev mode or log files

nope. I don't have any other info. I am wondering whether some java process was running but the task manager showed no. I am not sure what caused the issue.

**Comment by Emily-Jiang** [comment]
> We cannot reproduce the problem on Win VM.

oh, that was a shame. You can close this one for now. Next time I will ensure to take a screen shot and log files.

**Comment by gkwan-ibm** [comment]
Ok, I am going to close it.

More info definitely help. As I know, some very old versions of Maven may cause dev mode not work.
- mvn -version
- screenshot or copy of the console output
- log files

Thanks
