### ISSUE TITLE
Missing instructions in the guide 

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/guide-microprofile-openapi#32]
Under the section 'Generating the OpenAPI document for the inventory service' there is not an instruction to navigate to the `start` directory.  

At the very end of the guide (after the 'Testing the service' section) there is not an instruction to execute `mvn liberty:stop-server`.  This could be problematic if they do not stop the server and then immediately move onto another guide.  

Under the 'Getting Started' section, a quick explanation of the interactive view of the deployed APIs might be useful to this guide.  The view is interesting to look at but when you're looking at it for the first time a small explanation might help to make it more useful.

**Comment by gkwan-ibm** [comment]
- the first and second comments were addressed

**Comment by kathrynkodama** [comment]
Closed as concrete comments were addressed.

**Comment by gkwan-ibm** [comment]
PR #42
