### ISSUE TITLE
Multipane Issues

### ISSUE THREAD

**Issue by Rachelwrq** [OpenLiberty/guide-microprofile-openapi#33]
### Checklist for Post-Review
- [x] Read through guide, making sure that the flow of the guide is good
- [x] Click all links to make sure they lead to the correct place
- [ ] Make sure hotspots, code_commands and files are correct
- [x] Run Acrolinx

**Comment by Rachelwrq** [comment]
### Generating the OpenAPI document for the inventory service
#### Filtering the OpenAPI tree elements
- [ ] The instruction in the arrow should probably be changed to `Create the InventoryOASFilter class`
- [ ] The hotspot for the action arrow highlighted the whole file instead of the class.

### Testing the service
- [ ] `mvn verify` command is not in the green box

### In the end
- [ ] Under "Nice work! You did it!" The first sentence didn't end with "in Open Liberty"

**Comment by Rachelwrq** [comment]
- [ ] Acrolinx is under 70 for the first paragraph

**Comment by justineechen** [comment]
2nd round:
- [ ] guide author
- [ ] update to master
- [ ] mvn instructions
- [ ] if there is a clean comment, let consider or discuss it
- [ ] make sure liberty:stop-server before the testing (assumed testing is at the end)
