### ISSUE TITLE
Review feedback

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guide-microprofile-openapi#7]
- _The OpenAPI specification, previously known as the Swagger specification, defines a standard interface for **exposing** RESTful APIs._ For documenting and exposing RESTful APIs?

- Update to use common includes and proper repo name/link before publication.

- We should link to the MP 1.3 JavaDoc when ready.  This is covered by #3.

- _try one of the MicroProfile Config guides._ I'd prefer a link to our MP Config guides here too. Perhaps we can link via a search on the guides like https://openliberty.io/guides/?search=Config

- _No explicit tests exist to verify the correctness of the generated OpenAPI document._ Not sure if we really need this.  And, I would lead the section with the instruction to manually verify what is necessary.  Then, talk about the provided endpoint tests.

- _For more in-depth examples of MicroProfile OpenAPI, try one of the demo applications on the MicroProfile OpenAPI GitHub repository._ I am always wary of such a deep link.  This is nice the way it is done. Just need to keep an eye should the link changes.

- Is this really 15 minutes only?  Feels more than that but I'd go with number(s) from user testing.

**Comment by Kubik42** [comment]
- I originally thought that the OpenAPI spec was simply for exposing rest apis? Anyway, I changed the sentence to have "documenting and exposing RESTful APIs" like you suggested.
- Updated the gitclone to public one
- I added a yesterday. You can see it in one of the commits, but for some reason its not there anymore. Maybe somewhere was overwritten? Anyway, I added it back.
- Good point, added a link.
- Switched the paragraphs around.
- Yeah... 15 minutes might be too little for this guide. I changed it to 20.

Pull request open: https://github.com/OpenLiberty/draft-guide-microprofile-openapi/pull/8
