### ISSUE TITLE
Need to fix the daily build test after dev mode

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guide-microprofile-openapi#71]
Recent test failure: https://travis-ci.org/OpenLiberty/guide-microprofile-openapi/builds/620044684

**Comment by NimG98** [comment]
Daily build PR has been merged, will verify tmrw morning if it's running correctly.

**Comment by NimG98** [comment]
Daily build test is passing now, and `<install>` tag is being placed in LMP plugin.

The travis log: https://travis-ci.org/OpenLiberty/guide-microprofile-openapi/jobs/621092851#L290
