### ISSUE TITLE
OpenAPI: Suggestions

### ISSUE THREAD

**Issue by Ahmad-Ayyoub** [OpenLiberty/guide-microprofile-openapi#9]
Suggestions:

What you will learn:
- I don't think this paragraph "if you have read..." is needed (I do not see a value for it. why should I care about the new changes in the app ?).

- Now, point to the http://localhost:9080/openapi URL to see the generated OpenAPI tree.
-> has extra spaces below it.

- Filtering the OpenAPI tree elements -> I find this an extra thing, so I think it should be an optional section
- Using pre-generated OpenAPI documents -> this section should be switched with Filtering the OpenAPI tree elements . 

Because it shows another way of documenting the API + showing the missing info for `inventory/properties` -> which I was wondering where is that info coming from even tho no openAPI annotations were provided for `SystemResource.java `class. Then you showed that info in `Using pre-generated OpenAPI documents` section. (so the point is: showing everything first and then filtering is better).

- u have spaces between imports in ur classes. 

- run -> diff -r finish start (mine was a bit different, maybe i am wrong, just check)

- I was wondering why `http://localhost:9080/openapi/ui`  URL is skipped ( not explained). You just left them to deal with the ui in the test section. I think the UI is really powerful and useful because you do not want to just show that openAPI is just a boring doc. You can at least do one example on the ui. So that users can follow after. 

- Everything is working and I looked as well in the current PR. 

Otherwise, great job!

**Comment by yeekangc** [comment]
I am fine if we will remove the sentences around how the provided services differ from the other guides.  This is a detail.

Most of the feedback doesn't affect the integrity of the guide and can be considered separately or down the road.

If filtering can be made optional, that is fine too.  Then, a certain logic is assumed in the current guide.

**Comment by Kubik42** [comment]
- I want to keep the "If you have read..." since users that notice this change may wonder why the services have been put under a single app.
- We could reverse the order of the pre-genned doc and the filtering part. That wouldn't be bad at all, but lets do that later.
- The UI URL is not skipped. Its mentioned in the "Try what you'll build" section. I left it out from other sections because its much easier to demonstrate changes in the OpenAPI tree using yaml listing blocks.

**Comment by yeekangc** [comment]
Good with the thoughts and suggested actions.

**Comment by evelinec** [comment]
@Kubik42 I believe all the feedback here had been handled?

**Comment by Kubik42** [comment]
most of it yes, there
